fac_type_lookup = {
    9587: ("Agricultural Product Market", "Mercado de Productos Agrícolas"),
    4581: ("Airport", "Aeropuerto"),
    7996: ("Amusement Park", "Parque de Diversiones"),
    9718: ("Animal Park", "Parque de Animales"),
    3578: ("ATM", "Cajero Automático"),
    5512: ("Auto Dealership-Used Cars", "Agencia de Autos Usados"),
    7538: ("Auto Service & Maintenance", "Servicio y Mantenimiento Automotriz"),
    8699: ("Automobile Club", "Club Automovilístico"),
    5511: ("Auto Dealerships", "Agencia de Autos"),
    6000: ("Bank", "Banco"),
    9532: ("Bar or Pub", "Bar o Pub"),
    9051: ("Bicycle Parking", "Estacionamiento para Bicicletas"),
    9059: ("Bicycle Service", "Servicio de Bicicletas"),
    9050: ("Bicycle Sharing Location", "Estación de Bicicletas Compartidas"),
    9058: ("Bike Park", "Parque para Bicis"),
    9057: ("BMX Track", "Pista BMX"),
    9995: ("Bookstore", "Librería"),
    9999: ("Border Crossing", "Cruce Fronterizo"),
    7933: ("Bowling Centre", "Boliche"),
    4170: ("Bus Station", "Terminal de Autobuses"),
    5000: ("Business Facility", "Centro de Negocios"),
    9517: ("Campground", "Área de Campamento"),
    9056: ("Campsite", "Zona de Acampar"),
    9714: ("Cargo Centre", "Centro de Carga"),
    7985: ("Casino", "Casino"),
    9591: ("Cemetery", "Cementerio"),
    7832: ("Cinema", "Cine"),
    9121: ("City Hall", "Ayuntamiento"),
    7994: ("Civic/Community Centre", "Centro Cívico/Comunitario"),
    9537: ("Clothing Store", "Tienda de Ropa"),
    9996: ("Coffee Shop", "Cafetería"),
    4100: ("Commuter Rail Station", "Estación de Tren Suburbano"),
    9987: ("Consumer Electronics Store", "Tienda de Electrónica"),
    9535: ("Convenience Store", "Tienda de Conveniencia"),
    7990: ("Convention/Exhibition Centre", "Centro de Convenciones/Exposiciones"),
    9994: ("County Council", "Consejo del Condado"),
    9211: ("Court House", "Palacio de Justicia"),
    9722: ("Delivery Entrance", "Entrada de Entregas"),
    9545: ("Department Store", "Tienda Departamental"),
    9723: ("Dock", "Muelle"),
    9993: ("Embassy", "Embajada"),
    9598: ("EV Charging Station", "Estación de Carga para Vehículos Eléctricos"),
    4482: ("Ferry Terminal", "Terminal de Ferry"),
    9527: ("Fire Department", "Estación de Bomberos"),
    7992: ("Golf Course", "Campo de Golf"),
    9573: ("Golf Practice Range", "Campo de Práctica de Golf"),
    9525: ("Government Office", "Oficina Gubernamental"),
    5400: ("Grocery Store", "Tienda de Abarrotes"),
    9998: ("Hamlet", "Aldea"),
    8200: ("Higher Education", "Educación Superior"),
    9592: ("Highway Exit", "Salida de Carretera"),
    5999: ("Historical Monument", "Monumento Histórico"),
    9986: ("Home Improvement & Hardware Store", "Ferretería / Mejora del Hogar"),
    9560: ("Home Specialty Store", "Tienda Especializada en Hogar"),
    8060: ("Hospital", "Hospital"),
    7011: ("Hotel", "Hotel"),
    7998: ("Ice Skating Rink", "Pista de Patinaje"),
    9991: ("Industrial Zone", "Zona Industrial"),
    8231: ("Library", "Biblioteca"),
    9724: ("Loading Zone", "Zona de Carga"),
    9594: ("Lottery Booth", "Puesto de Lotería"),
    4493: ("Marina", "Marina"),
    9583: ("Medical Service", "Servicio Médico"),
    9725: ("Meeting Point", "Punto de Encuentro"),
    9715: ("Military Base", "Base Militar"),
    5571: ("Motorcycle Dealership", "Agencia de Motocicletas"),
    8410: ("Museum", "Museo"),
    9730: ("Named Intersection", "Cruce Nombrado"),
    4444: ("Named Place", "Lugar Nombrado"),
    9709: ("Neighbourhood", "Vecindario"),
    5813: ("Nightlife", "Vida Nocturna"),
    9988: ("Office Supply & Service Store", "Papelería / Servicios de Oficina"),
    7013: ("Other Accommodation", "Otro Alojamiento"),
    9053: ("Outdoor Service", "Servicio al Aire Libre"),
    7522: ("Park & Ride", "Estacionamiento para Transporte Público"),
    7947: ("Park/Recreation Area", "Parque / Área Recreativa"),
    7521: ("Parking Garage/House", "Estacionamiento Techado"),
    7520: ("Parking Lot", "Estacionamiento"),
    7929: ("Performing Arts", "Artes Escénicas"),
    5540: ("Petrol/Gasoline Station", "Gasolinera"),
    9565: ("Pharmacy", "Farmacia"),
    9992: ("Place of Worship", "Lugar de Culto"),
    9221: ("Police Station", "Estación de Policía"),
    9530: ("Post Office", "Oficina Postal"),
    9589: ("Public Restroom", "Baño Público"),
    4580: ("Public Sports Airport", "Aeropuerto Deportivo Público"),
    9054: ("Ranger Station", "Estación de Guardabosques"),
    7510: ("Rental Car Agency", "Agencia de Renta de Autos"),
    9595: ("Repair Services", "Servicios de Reparación"),
    9590: ("Residential Area/Building", "Área/Edificio Residencial"),
    7897: ("Rest Area", "Área de Descanso"),
    5800: ("Restaurant", "Restaurante"),
    9055: ("Running Track", "Pista para Correr"),
    8211: ("School", "Escuela"),
    6512: ("Shopping", "Compras"),
    7014: ("Ski Lift", "Teleférico"),
    7012: ("Ski Resort", "Centro de Esquí"),
    9567: ("Specialty Store", "Tienda Especializada"),
    9568: ("Sporting Goods Store", "Tienda de Deportes"),
    7997: ("Sports Centre", "Centro Deportivo"),
    7940: ("Sports Complex", "Complejo Deportivo"),
    9989: ("Taxi Stand", "Sitio de Taxis"),
    9597: ("Tea House", "Casa de Té"),
    9717: ("Tollbooth", "Caseta de Cobro"),
    7999: ("Tourist Attraction", "Atracción Turística"),
    7389: ("Tourist Information", "Información Turística"),
    9052: ("Trailhead", "Inicio de Sendero"),
    4013: ("Train Station", "Estación de Tren"),
    9596: ("Training Centre/Institute", "Centro/Instituto de Capacitación"),
    9593: ("Transportation Service", "Servicio de Transporte"),
    9719: ("Truck Dealership", "Agencia de Camiones"),
    9720: ("Truck Parking", "Estacionamiento para Camiones"),
    9522: ("Truck Stop/Plaza", "Parada/Plaza de Camiones"),
    9710: ("Weigh Station", "Estación de Pesaje"),
    2084: ("Winery", "Viñedo"),
}
